# Generated by Django 5.0.1 on 2024-01-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="institute",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_courses",
                to="institute.institute",
            ),
            preserve_default=False,
        ),
    ]
